"""amaran / Aputure product catalogue, generated from the Sidus Link APK assets.

Source: ``assets/fixtureProduct.json`` and ``assets/fixtureConfig.json``.
The five-character hex code is the prefix of the device name that a fixture
advertises inside its Mesh Provisioning Device UUID, e.g. ``400Y5-A1B2C3``.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class Product:
    """A known amaran / Aputure fixture."""

    hex_id: str
    name: str
    vendor: str
    series: str
    cct_min: int  # hundreds of Kelvin, 0 when the fixture is not bi-colour
    cct_max: int
    cct: bool
    hsi: bool
    rgb: bool
    gm: bool
    fine_dimming: bool

    @property
    def min_kelvin(self) -> int:
        """Lowest supported colour temperature in Kelvin."""
        return self.cct_min * 100

    @property
    def max_kelvin(self) -> int:
        """Highest supported colour temperature in Kelvin."""
        return self.cct_max * 100


PRODUCTS: dict[str, Product] = {
    "00005": Product(
        "00005",
        "LS C300d II",
        "Aputure",
        "Light Storm",
        56,
        56,
        False,
        False,
        False,
        False,
        False,
    ),
    "00015": Product(
        "00015",
        "LS 50d",
        "Aputure",
        "Light Storm",
        0,
        0,
        False,
        False,
        False,
        False,
        False,
    ),
    "00025": Product(
        "00025",
        "LS 50x",
        "Aputure",
        "Light Storm",
        0,
        0,
        False,
        False,
        False,
        False,
        False,
    ),
    "00035": Product(
        "00035",
        "LS 150x",
        "Aputure",
        "Light Storm",
        0,
        0,
        False,
        False,
        False,
        False,
        False,
    ),
    "00045": Product(
        "00045",
        "LS 300x",
        "Aputure",
        "Light Storm",
        27,
        65,
        True,
        False,
        False,
        False,
        False,
    ),
    "00055": Product(
        "00055",
        "LS 600d Pro",
        "Aputure",
        "Light Storm",
        56,
        56,
        False,
        False,
        False,
        False,
        True,
    ),
    "00065": Product(
        "00065",
        "LS 1500d",
        "Aputure",
        "Light Storm",
        0,
        0,
        False,
        False,
        False,
        False,
        False,
    ),
    "00075": Product(
        "00075",
        "LS 60d",
        "Aputure",
        "Light Storm",
        56,
        56,
        False,
        False,
        False,
        False,
        False,
    ),
    "00085": Product(
        "00085",
        "LS 60x",
        "Aputure",
        "Light Storm",
        27,
        65,
        True,
        False,
        False,
        False,
        False,
    ),
    "00095": Product(
        "00095",
        "LS 600x",
        "Aputure",
        "Light Storm",
        0,
        0,
        False,
        False,
        False,
        False,
        False,
    ),
    "000B5": Product(
        "000B5",
        "LS 350d",
        "Aputure",
        "Light Storm",
        0,
        0,
        False,
        False,
        False,
        False,
        False,
    ),
    "000C5": Product(
        "000C5",
        "LS 600d",
        "Aputure",
        "Light Storm",
        56,
        56,
        False,
        False,
        False,
        False,
        True,
    ),
    "000D5": Product(
        "000D5",
        "LS 600X Pro",
        "Aputure",
        "Light Storm",
        27,
        65,
        True,
        False,
        False,
        False,
        True,
    ),
    "000E5": Product(
        "000E5",
        "LS 1200d Pro",
        "Aputure",
        "Light Storm",
        56,
        56,
        False,
        False,
        False,
        False,
        True,
    ),
    "000F5": Product(
        "000F5",
        "MT Pro",
        "Aputure",
        "Mini",
        20,
        100,
        True,
        True,
        True,
        True,
        True,
    ),
    "000G5": Product(
        "000G5",
        "LS 600c Pro",
        "Aputure",
        "Light Storm",
        23,
        100,
        True,
        True,
        True,
        True,
        True,
    ),
    "000I5": Product(
        "000I5",
        "LS 1500x Pro",
        "Aputure",
        "Light Storm",
        0,
        0,
        False,
        False,
        False,
        False,
        False,
    ),
    "000J5": Product(
        "000J5",
        "Electro Storm XT26",
        "Aputure",
        "Electro Storm",
        27,
        65,
        True,
        False,
        False,
        True,
        True,
    ),
    "000K5": Product(
        "000K5",
        "Electro Storm CS15",
        "Aputure",
        "Electro Storm",
        20,
        100,
        True,
        True,
        True,
        True,
        True,
    ),
    "000L5": Product(
        "000L5",
        "LS 600c Pro II",
        "Aputure",
        "Light Storm",
        23,
        100,
        True,
        True,
        True,
        True,
        True,
    ),
    "000M5": Product(
        "000M5",
        "STORM 1200x",
        "Aputure",
        "STORM",
        25,
        100,
        True,
        False,
        False,
        True,
        True,
    ),
    "000N5": Product(
        "000N5",
        "STORM 80c",
        "Aputure",
        "STORM",
        18,
        200,
        True,
        True,
        True,
        True,
        True,
    ),
    "000P5": Product(
        "000P5",
        "STORM 1000c",
        "Aputure",
        "STORM",
        18,
        200,
        True,
        True,
        True,
        True,
        True,
    ),
    "000Q5": Product(
        "000Q5",
        "STORM 400x",
        "Aputure",
        "STORM",
        25,
        100,
        True,
        False,
        False,
        True,
        True,
    ),
    "000R5": Product(
        "000R5",
        "STORM XT52",
        "Aputure",
        "STORM",
        25,
        100,
        True,
        True,
        False,
        True,
        True,
    ),
    "000S5": Product(
        "000S5",
        "STORM 700x",
        "Aputure",
        "STORM",
        25,
        100,
        True,
        True,
        False,
        True,
        True,
    ),
    "02005": Product(
        "02005",
        "Nova P300c",
        "Aputure",
        "Nova",
        20,
        100,
        True,
        True,
        True,
        True,
        False,
    ),
    "02035": Product(
        "02035",
        "Nova P600C",
        "Aputure",
        "Nova",
        20,
        100,
        True,
        True,
        True,
        True,
        True,
    ),
    "02065": Product(
        "02065",
        "NOVA II 2x1",
        "Aputure",
        "Nova",
        18,
        200,
        True,
        True,
        True,
        True,
        True,
    ),
    "02075": Product(
        "02075",
        "NOVA 9° 2×1",
        "Aputure",
        "Nova",
        18,
        200,
        True,
        True,
        False,
        True,
        False,
    ),
    "02085": Product(
        "02085",
        "NOVA II 1x1",
        "Aputure",
        "Nova",
        18,
        200,
        True,
        True,
        True,
        True,
        True,
    ),
    "04005": Product(
        "04005",
        "B7c",
        "Aputure",
        "Accent",
        20,
        100,
        True,
        True,
        False,
        True,
        False,
    ),
    "05005": Product(
        "05005",
        "MC",
        "Aputure",
        "Mini",
        32,
        65,
        True,
        True,
        False,
        False,
        False,
    ),
    "05006": Product(
        "05006",
        "MC",
        "Aputure",
        "Mini",
        32,
        65,
        True,
        True,
        False,
        False,
        False,
    ),
    "05007": Product(
        "05007",
        "MC",
        "Aputure",
        "Mini",
        32,
        65,
        True,
        True,
        False,
        False,
        False,
    ),
    "05008": Product(
        "05008",
        "MC",
        "Aputure",
        "Mini",
        32,
        65,
        True,
        True,
        False,
        False,
        False,
    ),
    "05010": Product(
        "05010",
        "MC Pro",
        "Aputure",
        "Mini",
        20,
        100,
        True,
        True,
        True,
        True,
        True,
    ),
    "07006": Product(
        "07006",
        "INFINIBAR PB3",
        "Aputure",
        "INFINIBAR",
        20,
        100,
        True,
        True,
        True,
        True,
        True,
    ),
    "07007": Product(
        "07007",
        "INFINIBAR PB6",
        "Aputure",
        "INFINIBAR",
        20,
        100,
        True,
        True,
        True,
        True,
        True,
    ),
    "07008": Product(
        "07008",
        "INFINIBAR PB12",
        "Aputure",
        "INFINIBAR",
        20,
        100,
        True,
        True,
        True,
        True,
        True,
    ),
    "09005": Product(
        "09005",
        "INFINIMAT 4",
        "Aputure",
        "INFINIMAT",
        20,
        100,
        True,
        True,
        True,
        True,
        True,
    ),
    "09015": Product(
        "09015",
        "INFINIMAT 16",
        "Aputure",
        "INFINIMAT",
        20,
        100,
        True,
        True,
        True,
        True,
        True,
    ),
    "20005": Product(
        "20005",
        "SGC-H60",
        "SGC",
        "SGC-Tube",
        0,
        0,
        False,
        False,
        False,
        False,
        False,
    ),
    "20015": Product(
        "20015",
        "SGC-H120",
        "SGC",
        "SGC-Tube",
        0,
        0,
        False,
        False,
        False,
        False,
        False,
    ),
    "20025": Product(
        "20025",
        "SGC-P60",
        "SGC",
        "SGC-Tube",
        0,
        0,
        False,
        False,
        False,
        False,
        False,
    ),
    "20035": Product(
        "20035",
        "SGC-P120",
        "SGC",
        "SGC-Tube",
        0,
        0,
        False,
        False,
        False,
        False,
        False,
    ),
    "40005": Product(
        "40005",
        "amaran P60x",
        "amaran",
        "Panels",
        32,
        65,
        True,
        False,
        False,
        False,
        False,
    ),
    "40015": Product(
        "40015",
        "amaran P60c",
        "amaran",
        "Panels",
        25,
        75,
        True,
        True,
        False,
        True,
        False,
    ),
    "40025": Product(
        "40025",
        "amaran 100d",
        "amaran",
        "COB Lights",
        56,
        56,
        False,
        False,
        False,
        False,
        False,
    ),
    "40035": Product(
        "40035",
        "amaran 100x",
        "amaran",
        "COB Lights",
        27,
        65,
        True,
        False,
        False,
        False,
        False,
    ),
    "40045": Product(
        "40045",
        "amaran 200d",
        "amaran",
        "COB Lights",
        56,
        56,
        False,
        False,
        False,
        False,
        False,
    ),
    "40055": Product(
        "40055",
        "amaran 200x",
        "amaran",
        "COB Lights",
        27,
        65,
        True,
        False,
        False,
        False,
        False,
    ),
    "40065": Product(
        "40065",
        "amaran COB 60d",
        "amaran",
        "COB Lights",
        56,
        56,
        False,
        False,
        False,
        False,
        False,
    ),
    "40075": Product(
        "40075",
        "amaran COB 60x",
        "amaran",
        "COB Lights",
        27,
        65,
        True,
        False,
        False,
        False,
        False,
    ),
    "40085": Product(
        "40085",
        "amaran T2c ",
        "amaran",
        "Tubes",
        25,
        75,
        True,
        True,
        False,
        True,
        False,
    ),
    "40095": Product(
        "40095",
        "amaran T4c ",
        "amaran",
        "Tubes",
        25,
        75,
        True,
        True,
        False,
        True,
        False,
    ),
    "400A5": Product(
        "400A5",
        "amaran F7c",
        "amaran",
        "LED Mats",
        0,
        0,
        False,
        False,
        False,
        False,
        False,
    ),
    "400B5": Product(
        "400B5",
        "amaran F21x",
        "amaran",
        "LED Mats",
        25,
        75,
        True,
        False,
        False,
        False,
        False,
    ),
    "400C5": Product(
        "400C5",
        "amaran F21c",
        "amaran",
        "LED Mats",
        25,
        75,
        True,
        True,
        False,
        True,
        False,
    ),
    "400D5": Product(
        "400D5",
        "amaran F22x",
        "amaran",
        "LED Mats",
        25,
        75,
        True,
        False,
        False,
        False,
        False,
    ),
    "400E5": Product(
        "400E5",
        "amaran F22c",
        "amaran",
        "LED Mats",
        25,
        75,
        True,
        True,
        False,
        True,
        False,
    ),
    "400F5": Product(
        "400F5",
        "amaran SM5c",
        "amaran",
        "Other",
        32,
        65,
        True,
        True,
        False,
        True,
        False,
    ),
    "400G5": Product(
        "400G5",
        "amaran PT1c",
        "amaran",
        "Tubes",
        27,
        100,
        True,
        True,
        False,
        True,
        False,
    ),
    "400H5": Product(
        "400H5",
        "amaran PT2c",
        "amaran",
        "Tubes",
        27,
        100,
        True,
        True,
        False,
        True,
        False,
    ),
    "400I5": Product(
        "400I5",
        "amaran PT4c",
        "amaran",
        "Tubes",
        27,
        100,
        True,
        True,
        False,
        True,
        False,
    ),
    "400J5": Product(
        "400J5",
        "amaran 150c",
        "amaran",
        "COB Lights",
        25,
        75,
        True,
        True,
        False,
        True,
        False,
    ),
    "400K5": Product(
        "400K5",
        "amaran 300c",
        "amaran",
        "COB Lights",
        25,
        75,
        True,
        True,
        False,
        True,
        False,
    ),
    "400L5": Product(
        "400L5",
        "amaran 60d S",
        "amaran",
        "COB Lights",
        56,
        56,
        False,
        False,
        False,
        False,
        False,
    ),
    "400M5": Product(
        "400M5",
        "amaran 60x S",
        "amaran",
        "COB Lights",
        27,
        65,
        True,
        False,
        False,
        False,
        False,
    ),
    "400N5": Product(
        "400N5",
        "amaran 100d S",
        "amaran",
        "COB Lights",
        56,
        56,
        False,
        False,
        False,
        False,
        False,
    ),
    "400O5": Product(
        "400O5",
        "amaran 100x S",
        "amaran",
        "COB Lights",
        27,
        65,
        True,
        False,
        False,
        False,
        False,
    ),
    "400P5": Product(
        "400P5",
        "amaran 200d S",
        "amaran",
        "COB Lights",
        56,
        56,
        False,
        False,
        False,
        False,
        False,
    ),
    "400Q5": Product(
        "400Q5",
        "amaran 200x S",
        "amaran",
        "COB Lights",
        27,
        65,
        True,
        False,
        False,
        False,
        False,
    ),
    "400R5": Product(
        "400R5",
        "amaran 200c",
        "amaran",
        "COB Lights",
        25,
        75,
        True,
        True,
        False,
        True,
        False,
    ),
    "400S5": Product(
        "400S5",
        "amaran P40x",
        "amaran",
        "Panels",
        27,
        65,
        True,
        False,
        False,
        False,
        False,
    ),
    "400T5": Product(
        "400T5",
        "amaran Ace 25x",
        "amaran",
        "Mini Lights",
        27,
        65,
        True,
        False,
        False,
        False,
        False,
    ),
    "400U5": Product(
        "400U5",
        "amaran Ace 25c",
        "amaran",
        "Mini Lights",
        23,
        100,
        True,
        True,
        True,
        True,
        False,
    ),
    "400V5": Product(
        "400V5",
        "amaran Go",
        "amaran",
        "Mini Lights",
        27,
        65,
        True,
        False,
        False,
        False,
        False,
    ),
    "400W5": Product(
        "400W5",
        "amaran Pano 60c",
        "amaran",
        "Panels",
        23,
        100,
        True,
        True,
        True,
        True,
        False,
    ),
    "400X5": Product(
        "400X5",
        "amaran Pano 120c",
        "amaran",
        "Panels",
        23,
        100,
        True,
        True,
        True,
        True,
        False,
    ),
    "400Y5": Product(
        "400Y5",
        "amaran Verge",
        "amaran",
        "Panels",
        27,
        65,
        True,
        False,
        False,
        False,
        False,
    ),
    "400Z5": Product(
        "400Z5",
        "amaran Verge Max",
        "amaran",
        "Panels",
        27,
        65,
        True,
        False,
        False,
        False,
        False,
    ),
    "40105": Product(
        "40105",
        "amaran Tag RX",
        "amaran",
        "Other",
        0,
        0,
        False,
        False,
        False,
        False,
        False,
    ),
    "40115": Product(
        "40115",
        "amaran Tag TX",
        "amaran",
        "Other",
        0,
        0,
        False,
        False,
        False,
        False,
        False,
    ),
    "40145": Product(
        "40145",
        "amaran Ray 60c",
        "amaran",
        "COB Lights",
        23,
        100,
        True,
        True,
        True,
        True,
        False,
    ),
    "40165": Product(
        "40165",
        "amaran Ray 120c",
        "amaran",
        "COB Lights",
        23,
        100,
        True,
        True,
        True,
        True,
        False,
    ),
    "40185": Product(
        "40185",
        "amaran Ray 360c",
        "amaran",
        "COB Lights",
        23,
        100,
        True,
        True,
        True,
        True,
        False,
    ),
    "40195": Product(
        "40195",
        "amaran 300x",
        "amaran",
        "COB Lights",
        27,
        65,
        True,
        False,
        False,
        False,
        False,
    ),
    "401A5": Product(
        "401A5",
        "amaran Ray 660c",
        "amaran",
        "COB Lights",
        23,
        100,
        True,
        True,
        True,
        True,
        False,
    ),
    "401B5": Product(
        "401B5",
        "amaran Halo 60x",
        "amaran",
        "COB Lights",
        27,
        65,
        True,
        False,
        False,
        False,
        False,
    ),
    "401C5": Product(
        "401C5",
        "amaran Halo 100x",
        "amaran",
        "COB Lights",
        27,
        65,
        True,
        False,
        False,
        False,
        False,
    ),
    "401D5": Product(
        "401D5",
        "amaran Halo 200x",
        "amaran",
        "COB Lights",
        27,
        65,
        True,
        False,
        False,
        False,
        False,
    ),
    "401E5": Product(
        "401E5",
        "amaran Halo 300x",
        "amaran",
        "COB Lights",
        27,
        65,
        True,
        False,
        False,
        False,
        False,
    ),
    "401F5": Product(
        "401F5",
        "amaran Halo 600x",
        "amaran",
        "COB Lights",
        27,
        65,
        True,
        False,
        False,
        False,
        False,
    ),
    "EM005": Product(
        "EM005",
        "Motorized Yoke",
        "Aputure",
        "Motorized",
        0,
        0,
        False,
        False,
        False,
        False,
        False,
    ),
    "EM015": Product(
        "EM015",
        "Motorized F14 Fresnel",
        "Aputure",
        "Motorized",
        0,
        0,
        False,
        False,
        False,
        False,
        False,
    ),
}

#: Products this integration has been written and tested against.
SUPPORTED_HEX_IDS: frozenset[str] = frozenset({"400Y5", "400Z5"})


def parse_device_name(name: str) -> tuple[str, str] | None:
    """Split an advertised name like ``400Y5-A1B2C3`` into ``(hex_id, serial)``."""
    if "-" not in name:
        return None
    hex_id, _, serial = name.partition("-")
    if len(hex_id) != 5 or not serial:
        return None
    return hex_id, serial


def lookup(name: str) -> Product | None:
    """Resolve an advertised device name to a known product, if any."""
    parsed = parse_device_name(name)
    if parsed is None:
        return None
    return PRODUCTS.get(parsed[0])
